<?php
interface ILoggingContext {
    /**
    Give context information that will be used to log events generated by
    this item.
    */

    public function logPrefix();
        /**
        @return: Prefix used during log formatting to indicate context.
        @rtype: C{str}
        */
}
